baseURL = "/"

# website language
#网站语言
languageCode = "zh"

# [en, zh, ...] determines which i18n file to use
#确定要使用的i18n文件
defaultContentLanguage = "zh"

# website title
#标题
title = "Leo2c Blog"

# theme
#主题
theme = "LoveIt"

# whether to use git commit log to generate lastmod record
#是否使用git commit日志生成lastmod记录
enableGitInfo = false

# whether to include chinese/japanese/korean
# 是否包含中文/日文/韩文
hasCJKLanguage = false

# default amount of posts in each pages
# 每页的默认帖子数量
paginate = 12

# whether to use emoji code
# 是否使用表情符号代码
enableEmoji = true

# whether to use robots.txt
# 是否使用robots.txt
enableRobotsTXT = true

# [UA-XXXXXXXX-X] google analytics code
#  谷歌分析代码
googleAnalytics = ""

# copyright description used only for seo schema
# 版权说明仅用于seo模式
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

# date format
# 日期格式
dateFormatToUse = "2006-01-02"

# Markup related configuration in Hugo
# Hugo中与标记相关的配置
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  # 语法高亮
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  # Goldmark来自Hugo 0.60，是Markdown的默认库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      # 是否直接在文档中使用HTML标记
      unsafe = true
  # Table Of Contents settings
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author Info
[author]
  name = "leo2c"
  link = ""

# Sitemap Info
# 网站地图信息
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks Info (https://gohugo.io/content-management/urls/#permalinks)
# 永久链接信息
[Permalinks]
  posts = ":year/:month/:filename"

# Menu Info
# 菜单信息
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "posts"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "tags"
    weight = 2

  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "categories"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "about"
    weight = 4

  #[[menu.main]]
  #  identifier = "zh"
  #  pre = '<i class="fas fa-language fa-fw"></i>'
  #  name = ""
  #  title = "简体中文"
  #  url = "https://hugo-loveit-zh.netlify.com"
#[taxonomies]
 # tag = "tags"
 # series = "series"
 # category = "categories"
[params]
  # LoveIt theme version
  version = "0.1.X"
  # site description
  # 网站描述
  description = "Leo2c'personal blog,For recording and sharing Java Web information"
  # site keywords
  # 网站关键字
  keywords = ["Java","Spring"]
  # site default theme ("light", "dark", "auto")
  # 网站默认模版
  defaultTheme = "auto"

  # Home Page Info
  # 主页图片信息
  ##home mode ("post", "other")
  home_mode = "post"
  ## special amount of posts in each home post page
  ## 每个首页帖子页面上的特殊帖子数量
  home_paginate = 6
  ## URL of avatar shown in home page
  #主页中显示的头像的URL
  avatar = "images/avatar.png"
  ## subtitle shown in home page
  ## 主页中显示的字幕
  subtitle = "Welcome to leo2c's blog!"

  # whether to show social share links in post page
  # 是否在帖子页面中显示社交共享链接
  socialShare = false

  # Footer CopyRight Info
  # 页脚版权信息
  ## Site creation time
  ## 网站创建时间
  since = 2019
  ## ICP info only in China (HTML format is allowed)
  ## ICP信息仅在中国（允许HTML格式）
  icp = ""
  ## license info (HTML format is allowed)
  ## 许可证信息（允许HTML格式）
  license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # public git repo url to link lastmod git commit only then enableGitInfo is true
  # 公开git repo url链接lastmod git commit仅当enableGitInfo为true时
  gitRepo = "https://github.com/leo2c/leo2c.github.io"

  # mathematical formulas (KaTeX)
  [params.math]
    enable = true
    block_left_delimiter = ""
    block_right_delimiter = ""
    inline_left_delimiter = "$"
    inline_right_delimiter = "$"
    # KaTeX extension copy_tex
    copy_tex = true
    # KaTeX extension mhchem
    mhchem = true

  # whether to show link to Raw Markdown content of the post
  # 是否显示链接到帖子的原始Markdown内容
  linkToMarkdown = true

  # site verification code for Google/Bing/Yandex/Pinterest/Baidu
  # Google / Bing / Yandex / Pinterest / Baidu的网站验证代码
  google_verification = ""
  bing_verification = ""
  yandex_verification = ""
  pinterest_verification = ""
  baidu_verification = ""

  # CSS and JS Files CDN
  [params.cdn]
    ## for example '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.10.1/css/all.min.css" integrity="sha256-fdcFNFiBMrNfWL6OcAGQz6jDgNTRxnrLEd4vJYFWScE=" crossorigin="anonymous">'
    fontawesome_free_css = ''
    animate_css = ''
    gitalk_css = ''
    gitalk_js = ''
    valine_js = ''
    jquery_js = ''
    lazysizes_js = ''
    smooth_scroll_js = ''
    katex_css = ''
    katex_js = ''
    katex_auto_render_js = ''
    katex_copy_tex_css = ''
    katex_copy_tex_js = ''
    katex_mhchem_js = ''
    mermaid_js = ''
    echarts_js = ''
    echarts_macarons_js = ''
    typeit_js = ''
    jquery_countdown_js = ''
    aplayer_css = ''
    aplayer_js = ''
    meting_js = ''

  # Gravatar Info for preferred avatar in home page
  # 主页中首选头像的头像信息
  [params.gravatar]
    email = ""

  # Social Info in home page
  # 主页中的社交信息
  [params.social]
    GitHub = "leo2c"
    #Linkedin = "xxxx"
    #Twitter = "xxxx"
    #Instagram = "xxxx"
    Email = "leogo2c@gmail.com"
    #Facebook = "xxxx"
    #Telegram = "xxxx"
    #Medium = "xxxx"
    #Gitlab = "xxxx"
    #Youtubelegacy = "xxxx"
    #Youtubecustom = "xxxx"
    #Youtubechannel = "xxxx"
    #Tumblr ="xxxx"
    #Quora = "xxxx"
    #Keybase = "xxxx"
    #Pinterest = "xxxx"
    #Reddit = "xxxx"
    #Codepen = "xxxx"
    #FreeCodeCamp = "xxxx"
    #Bitbucket = "xxxx"
    #Stackoverflow = "xxxx"
    #Weibo = "xxxx"
    #Odnoklassniki = "xxxx"
    #VKontakte = "xxxx"
    #Flickr = "xxxx"
    #Xing = "xxxx"
    #Snapchat = "xxxx"
    #Soundcloud = "xxxx"
    #Spotify = "xxxx"
    #Bandcamp = "xxxx"
    #Paypal = "xxxx"
    #Fivehundredpx = "xxxx"
    #Mix = "xxxx"
    #Goodreads = "xxxx"
    #Lastfm = "xxxx"
    #Foursquare = "xxxx"
    #Hackernews = "xxxx"
    #Kickstarter = "xxxx"
    #Patreon = "xxxx"
    #Steam = "xxxx"
    #Twitch = "xxxx"
    #Strava = "xxxx"
    #Skype = "xxxx"
    #Whatsapp = "xxxx"
    #Zhihu = "xxxx"
    #Douban = "xxxx"
    #Angellist = "xxxx"
    #Slidershare = "xxxx"
    #Jsfiddle = "xxxx"
    #Deviantart = "xxxx"
    #Behance = "xxxx"
    #Dribble = "xxxx"
    #Wordpress = "xxxx"
    #Vine = "xxxx"
    #Googlescholar = "xxxx"
    #Researchgate = "xxxx"
    #Mastodon = "xxxx"
    #MastodonPrefix = "https://mastodon.technology/"
    #Thingiverse = "xxxx"
    #Devto = "xxxx"
    #Gitea = "xxxx"
    #XMPP = "xxxx"
    #Matrix ="xxxx"

  # Social Share Links in post page
  # 帖子页面中的社交共享链接
  [params.share]
    enable = true
    Twitter = true
    Facebook = true
    Reddit = true
    #Linkedin = true
    #Pinterest = true
    #HackerNews = true
    #Mix = true
    #Tumblr = true
    #VKontakte = true
    #Weibo = true

  # Publisher Info just for SEO
  # 仅适用于SEO的发布者信息
  [params.publisher]
    name = "leo2c"
    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40

  # Website Log Info just for SEO
  # 仅SEO的网站日志信息
  [params.logo]
    url = "logo.png"
    width = 127
    height = 40

  # Website Image Info just for SEO
  # 仅用于SEO的网站图像信息
  [params.image]
    url = "cover.png"
    width = 800
    height = 600

  # Disqus Comment Config (https://disqus.com/)
  # Disqus评论配置（https://disqus.com/）
  [params.disqus]
    # Disqus shortname to use Disqus in posts
    # Disqus短名称以在帖子中使用Disqus
    shortname = "leo2c"

  # Gittalk Comment Config (https://github.com/gitalk/gitalk)
  # Gittalk评论配置（https://github.com/gitalk/gitalk）
  [params.gitalk]
    owner = ""
    repo = ""
    clientId = ""
    clientSecret = ""

  # Valine Comment Config (https://github.com/xCss/Valine)
  # Valine 评论配置（https://github.com/xCss/Valine）
  [params.valine]
    enable = false
    appId = ""
    appKey = ""
    placeholder = "Your comment ..."
    notify = false
    verify = true
    avatar = "mp"
    #meta= ""
    pageSize = 10
    visitor = true
    recordIP = true

  # Facebook Comment Config (https://developers.facebook.com/docs/plugins/comments)
  # Facebook 评论设置
  [params.facebook]
    enable = false
    width = "100%"
    numPosts = 10
    appId = ""
    languageCode = "en_US"

# Privacy Info (https://gohugo.io/about/hugo-and-gdpr/)
# 隐私信息
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true

  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
# 生成输出.md文件的选项
[mediaTypes]
#文件类型
  [mediaTypes."text/plain"]
  #后缀
    suffixes = ["md"]

# Options to make output .md files
# 生成输出.md文件的选项
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
# 制作hugo输出文件的选项
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
